### ISSUE TITLE
first and second strand

### ISSUE THREAD

**Issue by HollyLeanneBrown** [BrentLab/database_files#2]
We don't have a first and second strand protocol for the old Solexa Prep. It should be SuperScriptIII.

**Comment by cmatKhan** [comment]
I need these to be a little bit more descriptive. eg)

s1cDNAprotocol should have the following options:

  - s1prep1
  - s1prep2

s2CDNAprotocol:

...

With this as it stands, I don't know what to update or what needs to be fixed in the sheets
