### ISSUE TITLE
Case Sensitive names?

### ISSUE THREAD

**Issue by JungJeffery** [BrentLab/database_files#5]
Hey. I don't know if it's your intention to make the name columns case sensitive. I noticed that some sheets were not getting included in the output of the queryDB command, so I looked around a bit and found that naming inconsistencies in fastq files such as H.BROWN to H.Brown do not get joined properly. Can you guys either fix all the sheets so that all the names are consistent? Or perhaps it makes more sense to just code it such that names(and probably some other columns) are not case sensitive.

I'll put two example sheets here:
s1CDNASample_hbrown_05.25.20.xlsx (H.BROWN)
s2CDNASample_hbrown_05.25.20.xlsx (H.Brown)

**Comment by cmatKhan** [comment]
I will cast all key columns to upper case before merging.

However, when you find something like that in the sheets, please let the enter-er know. If it is a retrofit sheet, it is easy to correct. If it is not, the enter-er should know what sheets connect from bioSample --> fastq and it will probably be easier for them to fix

**Comment by cmatKhan** [comment]
resolved
